/*******************************************************************************
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *******************************************************************************/


package org.noerp.common;

import java.util.LinkedHashMap;
import java.util.Map;


public final class JsLanguageFilesMapping {

    // DO NOT EDIT THIS FILE!  THIS IS AUTO GENERATED AND WILL GET WRITTEN OVER PERIODICALLY WHEN THE DATA CHANGE
    // Rather use the createJsLanguageFileMapping service to create or update it. You will still need to compile thereafter

    public static class datejs {

        private static Map<String, String> localeFiles = new LinkedHashMap<String, String>();
        private static String defaultDateJs = "/assets/jquery/plugins/datejs/date-en-US.js";

        static {
            localeFiles.put("sq", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("sq_AL", "/assets/jquery/plugins/datejs/date-sq-AL.js");
            localeFiles.put("ar", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("ar_DZ", "/assets/jquery/plugins/datejs/date-ar-DZ.js");
            localeFiles.put("ar_BH", "/assets/jquery/plugins/datejs/date-ar-BH.js");
            localeFiles.put("ar_EG", "/assets/jquery/plugins/datejs/date-ar-EG.js");
            localeFiles.put("ar_IQ", "/assets/jquery/plugins/datejs/date-ar-IQ.js");
            localeFiles.put("ar_JO", "/assets/jquery/plugins/datejs/date-ar-JO.js");
            localeFiles.put("ar_KW", "/assets/jquery/plugins/datejs/date-ar-KW.js");
            localeFiles.put("ar_LB", "/assets/jquery/plugins/datejs/date-ar-LB.js");
            localeFiles.put("ar_LY", "/assets/jquery/plugins/datejs/date-ar-LY.js");
            localeFiles.put("ar_MA", "/assets/jquery/plugins/datejs/date-ar-MA.js");
            localeFiles.put("ar_OM", "/assets/jquery/plugins/datejs/date-ar-OM.js");
            localeFiles.put("ar_QA", "/assets/jquery/plugins/datejs/date-ar-QA.js");
            localeFiles.put("ar_SA", "/assets/jquery/plugins/datejs/date-ar-SA.js");
            localeFiles.put("ar_SD", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("ar_SY", "/assets/jquery/plugins/datejs/date-ar-SY.js");
            localeFiles.put("ar_TN", "/assets/jquery/plugins/datejs/date-ar-TN.js");
            localeFiles.put("ar_AE", "/assets/jquery/plugins/datejs/date-ar-AE.js");
            localeFiles.put("ar_YE", "/assets/jquery/plugins/datejs/date-ar-YE.js");
            localeFiles.put("be", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("be_BY", "/assets/jquery/plugins/datejs/date-be-BY.js");
            localeFiles.put("bg", "/assets/jquery/plugins/datejs/date-bg-BG.js");
            localeFiles.put("bg_BG", "/assets/jquery/plugins/datejs/date-bg-BG.js");
            localeFiles.put("ca", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("ca_ES", "/assets/jquery/plugins/datejs/date-ca-ES.js");
            localeFiles.put("zh", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("zh_CN", "/assets/jquery/plugins/datejs/date-zh-CN.js");
            localeFiles.put("zh_HK", "/assets/jquery/plugins/datejs/date-zh-HK.js");
            localeFiles.put("zh_SG", "/assets/jquery/plugins/datejs/date-zh-SG.js");
            localeFiles.put("zh_TW", "/assets/jquery/plugins/datejs/date-zh-TW.js");
            localeFiles.put("hr", "/assets/jquery/plugins/datejs/date-hr-HR.js");
            localeFiles.put("hr_HR", "/assets/jquery/plugins/datejs/date-hr-HR.js");
            localeFiles.put("cs", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("cs_CZ", "/assets/jquery/plugins/datejs/date-cs-CZ.js");
            localeFiles.put("da", "/assets/jquery/plugins/datejs/date-da-DA.js");
            localeFiles.put("da_DK", "/assets/jquery/plugins/datejs/date-da-DK.js");
            localeFiles.put("nl", "/assets/jquery/plugins/datejs/date-nl-NL.js");
            localeFiles.put("nl_BE", "/assets/jquery/plugins/datejs/date-nl-BE.js");
            localeFiles.put("nl_NL", "/assets/jquery/plugins/datejs/date-nl-NL.js");
            localeFiles.put("en", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("en_AU", "/assets/jquery/plugins/datejs/date-en-AU.js");
            localeFiles.put("en_CA", "/assets/jquery/plugins/datejs/date-en-CA.js");
            localeFiles.put("en_IN", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("en_IE", "/assets/jquery/plugins/datejs/date-en-IE.js");
            localeFiles.put("en_MT", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("en_NZ", "/assets/jquery/plugins/datejs/date-en-NZ.js");
            localeFiles.put("en_PH", "/assets/jquery/plugins/datejs/date-en-PH.js");
            localeFiles.put("en_SG", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("en_ZA", "/assets/jquery/plugins/datejs/date-en-ZA.js");
            localeFiles.put("en_GB", "/assets/jquery/plugins/datejs/date-en-GB.js");
            localeFiles.put("en_US", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("et", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("et_EE", "/assets/jquery/plugins/datejs/date-et-EE.js");
            localeFiles.put("fi", "/assets/jquery/plugins/datejs/date-fi-FI.js");
            localeFiles.put("fi_FI", "/assets/jquery/plugins/datejs/date-fi-FI.js");
            localeFiles.put("fr", "/assets/jquery/plugins/datejs/date-fr-FR.js");
            localeFiles.put("fr_BE", "/assets/jquery/plugins/datejs/date-fr-BE.js");
            localeFiles.put("fr_CA", "/assets/jquery/plugins/datejs/date-fr-CA.js");
            localeFiles.put("fr_FR", "/assets/jquery/plugins/datejs/date-fr-FR.js");
            localeFiles.put("fr_LU", "/assets/jquery/plugins/datejs/date-fr-LU.js");
            localeFiles.put("fr_CH", "/assets/jquery/plugins/datejs/date-fr-CH.js");
            localeFiles.put("de", "/assets/jquery/plugins/datejs/date-de-DE.js");
            localeFiles.put("de_AT", "/assets/jquery/plugins/datejs/date-de-AT.js");
            localeFiles.put("de_DE", "/assets/jquery/plugins/datejs/date-de-DE.js");
            localeFiles.put("de_LU", "/assets/jquery/plugins/datejs/date-de-LU.js");
            localeFiles.put("de_CH", "/assets/jquery/plugins/datejs/date-de-CH.js");
            localeFiles.put("el", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("el_CY", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("el_GR", "/assets/jquery/plugins/datejs/date-el-GR.js");
            localeFiles.put("iw", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("iw_IL", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("hi_IN", "/assets/jquery/plugins/datejs/date-hi-IN.js");
            localeFiles.put("hu", "/assets/jquery/plugins/datejs/date-hu-HU.js");
            localeFiles.put("hu_HU", "/assets/jquery/plugins/datejs/date-hu-HU.js");
            localeFiles.put("is", "/assets/jquery/plugins/datejs/date-is-IS.js");
            localeFiles.put("is_IS", "/assets/jquery/plugins/datejs/date-is-IS.js");
            localeFiles.put("in", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("in_ID", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("ga", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("ga_IE", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("it", "/assets/jquery/plugins/datejs/date-it-IT.js");
            localeFiles.put("it_IT", "/assets/jquery/plugins/datejs/date-it-IT.js");
            localeFiles.put("it_CH", "/assets/jquery/plugins/datejs/date-it-CH.js");
            localeFiles.put("ja", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("ja_JP", "/assets/jquery/plugins/datejs/date-ja-JP.js");
            localeFiles.put("ja_JP_JP", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("ko", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("ko_KR", "/assets/jquery/plugins/datejs/date-ko-KR.js");
            localeFiles.put("lv", "/assets/jquery/plugins/datejs/date-lv-LV.js");
            localeFiles.put("lv_LV", "/assets/jquery/plugins/datejs/date-lv-LV.js");
            localeFiles.put("lt", "/assets/jquery/plugins/datejs/date-lt-LT.js");
            localeFiles.put("lt_LT", "/assets/jquery/plugins/datejs/date-lt-LT.js");
            localeFiles.put("mk", "/assets/jquery/plugins/datejs/date-mk-MK.js");
            localeFiles.put("mk_MK", "/assets/jquery/plugins/datejs/date-mk-MK.js");
            localeFiles.put("ms", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("ms_MY", "/assets/jquery/plugins/datejs/date-ms-MY.js");
            localeFiles.put("mt", "/assets/jquery/plugins/datejs/date-mt-MT.js");
            localeFiles.put("mt_MT", "/assets/jquery/plugins/datejs/date-mt-MT.js");
            localeFiles.put("no", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("no_NO", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("no_NO_NY", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("pl", "/assets/jquery/plugins/datejs/date-pl-PL.js");
            localeFiles.put("pl_PL", "/assets/jquery/plugins/datejs/date-pl-PL.js");
            localeFiles.put("pt", "/assets/jquery/plugins/datejs/date-pt-PT.js");
            localeFiles.put("pt_BR", "/assets/jquery/plugins/datejs/date-pt-BR.js");
            localeFiles.put("pt_PT", "/assets/jquery/plugins/datejs/date-pt-PT.js");
            localeFiles.put("ro", "/assets/jquery/plugins/datejs/date-ro-RO.js");
            localeFiles.put("ro_RO", "/assets/jquery/plugins/datejs/date-ro-RO.js");
            localeFiles.put("ru", "/assets/jquery/plugins/datejs/date-ru-RU.js");
            localeFiles.put("ru_RU", "/assets/jquery/plugins/datejs/date-ru-RU.js");
            localeFiles.put("sr", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("sr_BA", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("sr_ME", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("sr_CS", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("sr_RS", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("sk", "/assets/jquery/plugins/datejs/date-sk-SK.js");
            localeFiles.put("sk_SK", "/assets/jquery/plugins/datejs/date-sk-SK.js");
            localeFiles.put("sl", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("sl_SI", "/assets/jquery/plugins/datejs/date-sl-SI.js");
            localeFiles.put("es", "/assets/jquery/plugins/datejs/date-es-ES.js");
            localeFiles.put("es_AR", "/assets/jquery/plugins/datejs/date-es-AR.js");
            localeFiles.put("es_BO", "/assets/jquery/plugins/datejs/date-es-BO.js");
            localeFiles.put("es_CL", "/assets/jquery/plugins/datejs/date-es-CL.js");
            localeFiles.put("es_CO", "/assets/jquery/plugins/datejs/date-es-CO.js");
            localeFiles.put("es_CR", "/assets/jquery/plugins/datejs/date-es-CR.js");
            localeFiles.put("es_DO", "/assets/jquery/plugins/datejs/date-es-DO.js");
            localeFiles.put("es_EC", "/assets/jquery/plugins/datejs/date-es-EC.js");
            localeFiles.put("es_SV", "/assets/jquery/plugins/datejs/date-es-SV.js");
            localeFiles.put("es_GT", "/assets/jquery/plugins/datejs/date-es-GT.js");
            localeFiles.put("es_HN", "/assets/jquery/plugins/datejs/date-es-HN.js");
            localeFiles.put("es_MX", "/assets/jquery/plugins/datejs/date-es-MX.js");
            localeFiles.put("es_NI", "/assets/jquery/plugins/datejs/date-es-NI.js");
            localeFiles.put("es_PA", "/assets/jquery/plugins/datejs/date-es-PA.js");
            localeFiles.put("es_PY", "/assets/jquery/plugins/datejs/date-es-PY.js");
            localeFiles.put("es_PE", "/assets/jquery/plugins/datejs/date-es-PE.js");
            localeFiles.put("es_PR", "/assets/jquery/plugins/datejs/date-es-PR.js");
            localeFiles.put("es_ES", "/assets/jquery/plugins/datejs/date-es-ES.js");
            localeFiles.put("es_US", "/assets/jquery/plugins/datejs/date-es-ES.js");
            localeFiles.put("es_UY", "/assets/jquery/plugins/datejs/date-es-UY.js");
            localeFiles.put("es_VE", "/assets/jquery/plugins/datejs/date-es-VE.js");
            localeFiles.put("sv", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("sv_SE", "/assets/jquery/plugins/datejs/date-sv-SE.js");
            localeFiles.put("th", "/assets/jquery/plugins/datejs/date-th-TH.js");
            localeFiles.put("th_TH", "/assets/jquery/plugins/datejs/date-th-TH.js");
            localeFiles.put("th_TH_TH", "/assets/jquery/plugins/datejs/date-th-TH.js");
            localeFiles.put("tr", "/assets/jquery/plugins/datejs/date-tr-TR.js");
            localeFiles.put("tr_TR", "/assets/jquery/plugins/datejs/date-tr-TR.js");
            localeFiles.put("uk", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("uk_UA", "/assets/jquery/plugins/datejs/date-uk-UA.js");
            localeFiles.put("vi", "/assets/jquery/plugins/datejs/date-en-US.js");
            localeFiles.put("vi_VN", "/assets/jquery/plugins/datejs/date-vi-VN.js");
        }

        public static String getFilePath(String locale) {
            if (datejs.localeFiles.containsKey(locale)) {
                return datejs.localeFiles.get(locale);
            }
            return datejs.defaultDateJs;
        }

    }

    public static class jquery {
        private static Map<String, String> localeFiles = new LinkedHashMap<String, String>();
        private static String defaultDateJs = "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js";

        static {
            localeFiles.put("sq", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sq.js");
            localeFiles.put("sq_AL", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sq.js");
            localeFiles.put("ar", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_DZ", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_BH", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_EG", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_IQ", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_JO", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_KW", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_LB", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_LY", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_MA", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_OM", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_QA", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_SA", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_SD", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_SY", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_TN", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_AE", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("ar_YE", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ar.js");
            localeFiles.put("be", "/assets/jquery/ui/i18n/jquery.ui.datepicker-be.js");
            localeFiles.put("be_BY", "/assets/jquery/ui/i18n/jquery.ui.datepicker-be.js");
            localeFiles.put("bg", "/assets/jquery/ui/i18n/jquery.ui.datepicker-bg.js");
            localeFiles.put("bg_BG", "/assets/jquery/ui/i18n/jquery.ui.datepicker-bg.js");
            localeFiles.put("ca", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ca.js");
            localeFiles.put("ca_ES", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ca.js");
            localeFiles.put("zh", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("zh_CN", "/assets/jquery/ui/i18n/jquery.ui.datepicker-zh-CN.js");
            localeFiles.put("zh_HK", "/assets/jquery/ui/i18n/jquery.ui.datepicker-zh-HK.js");
            localeFiles.put("zh_SG", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("zh_TW", "/assets/jquery/ui/i18n/jquery.ui.datepicker-zh-TW.js");
            localeFiles.put("hr", "/assets/jquery/ui/i18n/jquery.ui.datepicker-hr.js");
            localeFiles.put("hr_HR", "/assets/jquery/ui/i18n/jquery.ui.datepicker-hr.js");
            localeFiles.put("cs", "/assets/jquery/ui/i18n/jquery.ui.datepicker-cs.js");
            localeFiles.put("cs_CZ", "/assets/jquery/ui/i18n/jquery.ui.datepicker-cs.js");
            localeFiles.put("da", "/assets/jquery/ui/i18n/jquery.ui.datepicker-da.js");
            localeFiles.put("da_DK", "/assets/jquery/ui/i18n/jquery.ui.datepicker-da.js");
            localeFiles.put("nl", "/assets/jquery/ui/i18n/jquery.ui.datepicker-nl.js");
            localeFiles.put("nl_BE", "/assets/jquery/ui/i18n/jquery.ui.datepicker-nl.js");
            localeFiles.put("nl_NL", "/assets/jquery/ui/i18n/jquery.ui.datepicker-nl.js");
            localeFiles.put("en", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("en_AU", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("en_CA", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("en_IN", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("en_IE", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("en_MT", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("en_NZ", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("en_PH", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("en_SG", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("en_ZA", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("en_GB", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("en_US", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("et", "/assets/jquery/ui/i18n/jquery.ui.datepicker-et.js");
            localeFiles.put("et_EE", "/assets/jquery/ui/i18n/jquery.ui.datepicker-et.js");
            localeFiles.put("fi", "/assets/jquery/ui/i18n/jquery.ui.datepicker-fi.js");
            localeFiles.put("fi_FI", "/assets/jquery/ui/i18n/jquery.ui.datepicker-fi.js");
            localeFiles.put("fr", "/assets/jquery/ui/i18n/jquery.ui.datepicker-fr.js");
            localeFiles.put("fr_BE", "/assets/jquery/ui/i18n/jquery.ui.datepicker-fr.js");
            localeFiles.put("fr_CA", "/assets/jquery/ui/i18n/jquery.ui.datepicker-fr.js");
            localeFiles.put("fr_FR", "/assets/jquery/ui/i18n/jquery.ui.datepicker-fr.js");
            localeFiles.put("fr_LU", "/assets/jquery/ui/i18n/jquery.ui.datepicker-fr.js");
            localeFiles.put("fr_CH", "/assets/jquery/ui/i18n/jquery.ui.datepicker-fr.js");
            localeFiles.put("de", "/assets/jquery/ui/i18n/jquery.ui.datepicker-de.js");
            localeFiles.put("de_AT", "/assets/jquery/ui/i18n/jquery.ui.datepicker-de.js");
            localeFiles.put("de_DE", "/assets/jquery/ui/i18n/jquery.ui.datepicker-de.js");
            localeFiles.put("de_LU", "/assets/jquery/ui/i18n/jquery.ui.datepicker-de.js");
            localeFiles.put("de_CH", "/assets/jquery/ui/i18n/jquery.ui.datepicker-de.js");
            localeFiles.put("el", "/assets/jquery/ui/i18n/jquery.ui.datepicker-el.js");
            localeFiles.put("el_CY", "/assets/jquery/ui/i18n/jquery.ui.datepicker-el.js");
            localeFiles.put("el_GR", "/assets/jquery/ui/i18n/jquery.ui.datepicker-el.js");
            localeFiles.put("iw", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("iw_IL", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("hi_IN", "/assets/jquery/ui/i18n/jquery.ui.datepicker-hi.js");
            localeFiles.put("hu", "/assets/jquery/ui/i18n/jquery.ui.datepicker-hu.js");
            localeFiles.put("hu_HU", "/assets/jquery/ui/i18n/jquery.ui.datepicker-hu.js");
            localeFiles.put("is", "/assets/jquery/ui/i18n/jquery.ui.datepicker-is.js");
            localeFiles.put("is_IS", "/assets/jquery/ui/i18n/jquery.ui.datepicker-is.js");
            localeFiles.put("in", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("in_ID", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("ga", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("ga_IE", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("it", "/assets/jquery/ui/i18n/jquery.ui.datepicker-it.js");
            localeFiles.put("it_IT", "/assets/jquery/ui/i18n/jquery.ui.datepicker-it.js");
            localeFiles.put("it_CH", "/assets/jquery/ui/i18n/jquery.ui.datepicker-it.js");
            localeFiles.put("ja", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ja.js");
            localeFiles.put("ja_JP", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ja.js");
            localeFiles.put("ja_JP_JP", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ja.js");
            localeFiles.put("ko", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ko.js");
            localeFiles.put("ko_KR", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ko.js");
            localeFiles.put("lv", "/assets/jquery/ui/i18n/jquery.ui.datepicker-lv.js");
            localeFiles.put("lv_LV", "/assets/jquery/ui/i18n/jquery.ui.datepicker-lv.js");
            localeFiles.put("lt", "/assets/jquery/ui/i18n/jquery.ui.datepicker-lt.js");
            localeFiles.put("lt_LT", "/assets/jquery/ui/i18n/jquery.ui.datepicker-lt.js");
            localeFiles.put("mk", "/assets/jquery/ui/i18n/jquery.ui.datepicker-mk.js");
            localeFiles.put("mk_MK", "/assets/jquery/ui/i18n/jquery.ui.datepicker-mk.js");
            localeFiles.put("ms", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ms.js");
            localeFiles.put("ms_MY", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ms.js");
            localeFiles.put("mt", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("mt_MT", "/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js");
            localeFiles.put("no", "/assets/jquery/ui/i18n/jquery.ui.datepicker-no.js");
            localeFiles.put("no_NO", "/assets/jquery/ui/i18n/jquery.ui.datepicker-no.js");
            localeFiles.put("no_NO_NY", "/assets/jquery/ui/i18n/jquery.ui.datepicker-no.js");
            localeFiles.put("pl", "/assets/jquery/ui/i18n/jquery.ui.datepicker-pl.js");
            localeFiles.put("pl_PL", "/assets/jquery/ui/i18n/jquery.ui.datepicker-pl.js");
            localeFiles.put("pt", "/assets/jquery/ui/i18n/jquery.ui.datepicker-pt.js");
            localeFiles.put("pt_BR", "/assets/jquery/ui/i18n/jquery.ui.datepicker-pt.js");
            localeFiles.put("pt_PT", "/assets/jquery/ui/i18n/jquery.ui.datepicker-pt.js");
            localeFiles.put("ro", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ro.js");
            localeFiles.put("ro_RO", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ro.js");
            localeFiles.put("ru", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ru.js");
            localeFiles.put("ru_RU", "/assets/jquery/ui/i18n/jquery.ui.datepicker-ru.js");
            localeFiles.put("sr", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sr.js");
            localeFiles.put("sr_BA", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sr.js");
            localeFiles.put("sr_ME", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sr.js");
            localeFiles.put("sr_CS", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sr.js");
            localeFiles.put("sr_RS", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sr.js");
            localeFiles.put("sk", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sk.js");
            localeFiles.put("sk_SK", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sk.js");
            localeFiles.put("sl", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sl.js");
            localeFiles.put("sl_SI", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sl.js");
            localeFiles.put("es", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_AR", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_BO", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_CL", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_CO", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_CR", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_DO", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_EC", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_SV", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_GT", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_HN", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_MX", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_NI", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_PA", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_PY", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_PE", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_PR", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_ES", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_US", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_UY", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("es_VE", "/assets/jquery/ui/i18n/jquery.ui.datepicker-es.js");
            localeFiles.put("sv", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sv.js");
            localeFiles.put("sv_SE", "/assets/jquery/ui/i18n/jquery.ui.datepicker-sv.js");
            localeFiles.put("th", "/assets/jquery/ui/i18n/jquery.ui.datepicker-th.js");
            localeFiles.put("th_TH", "/assets/jquery/ui/i18n/jquery.ui.datepicker-th.js");
            localeFiles.put("th_TH_TH", "/assets/jquery/ui/i18n/jquery.ui.datepicker-th.js");
            localeFiles.put("tr", "/assets/jquery/ui/i18n/jquery.ui.datepicker-tr.js");
            localeFiles.put("tr_TR", "/assets/jquery/ui/i18n/jquery.ui.datepicker-tr.js");
            localeFiles.put("uk", "/assets/jquery/ui/i18n/jquery.ui.datepicker-uk.js");
            localeFiles.put("uk_UA", "/assets/jquery/ui/i18n/jquery.ui.datepicker-uk.js");
            localeFiles.put("vi", "/assets/jquery/ui/i18n/jquery.ui.datepicker-vi.js");
            localeFiles.put("vi_VN", "/assets/jquery/ui/i18n/jquery.ui.datepicker-vi.js");
        }

        public static String getFilePath(String locale) {
            if (datejs.localeFiles.containsKey(locale)) {
                return jquery.localeFiles.get(locale);
            }
            return jquery.defaultDateJs;
        }

    }

    public static class validation {
        private static Map<String, String> localeFiles = new LinkedHashMap<String, String>();
        private static String defaultValidation = "/assets/webapp/assets/jquery/plugins/validate/localization/messages_en.js";

        static {
            localeFiles.put("sq", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("sq_AL", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("ar", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_DZ", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_BH", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_EG", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_IQ", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_JO", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_KW", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_LB", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_LY", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_MA", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_OM", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_QA", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_SA", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_SD", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_SY", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_TN", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_AE", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("ar_YE", "/assets/jquery/plugins/validate/localization/messages_ar.js");
            localeFiles.put("be", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("be_BY", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("bg", "/assets/jquery/plugins/validate/localization/messages_bg.js");
            localeFiles.put("bg_BG", "/assets/jquery/plugins/validate/localization/messages_bg.js");
            localeFiles.put("ca", "/assets/jquery/plugins/validate/localization/messages_ca.js");
            localeFiles.put("ca_ES", "/assets/jquery/plugins/validate/localization/messages_ca.js");
            localeFiles.put("zh", "/assets/jquery/plugins/validate/localization/messages_zh.js");
            localeFiles.put("zh_CN", "/assets/jquery/plugins/validate/localization/messages_zh.js");
            localeFiles.put("zh_HK", "/assets/jquery/plugins/validate/localization/messages_zh.js");
            localeFiles.put("zh_SG", "/assets/jquery/plugins/validate/localization/messages_zh.js");
            localeFiles.put("zh_TW", "/assets/jquery/plugins/validate/localization/messages_zh_TW.js");
            localeFiles.put("hr", "/assets/jquery/plugins/validate/localization/messages_hr.js");
            localeFiles.put("hr_HR", "/assets/jquery/plugins/validate/localization/messages_hr.js");
            localeFiles.put("cs", "/assets/jquery/plugins/validate/localization/messages_cs.js");
            localeFiles.put("cs_CZ", "/assets/jquery/plugins/validate/localization/messages_cs.js");
            localeFiles.put("da", "/assets/jquery/plugins/validate/localization/messages_da.js");
            localeFiles.put("da_DK", "/assets/jquery/plugins/validate/localization/messages_da.js");
            localeFiles.put("nl", "/assets/jquery/plugins/validate/localization/messages_nl.js");
            localeFiles.put("nl_BE", "/assets/jquery/plugins/validate/localization/messages_nl.js");
            localeFiles.put("nl_NL", "/assets/jquery/plugins/validate/localization/messages_nl.js");
            localeFiles.put("en", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("en_AU", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("en_CA", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("en_IN", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("en_IE", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("en_MT", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("en_NZ", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("en_PH", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("en_SG", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("en_ZA", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("en_GB", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("en_US", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("et", "/assets/jquery/plugins/validate/localization/messages_et.js");
            localeFiles.put("et_EE", "/assets/jquery/plugins/validate/localization/messages_et.js");
            localeFiles.put("fi", "/assets/jquery/plugins/validate/localization/messages_fi.js");
            localeFiles.put("fi_FI", "/assets/jquery/plugins/validate/localization/messages_fi.js");
            localeFiles.put("fr", "/assets/jquery/plugins/validate/localization/messages_fr.js");
            localeFiles.put("fr_BE", "/assets/jquery/plugins/validate/localization/messages_fr.js");
            localeFiles.put("fr_CA", "/assets/jquery/plugins/validate/localization/messages_fr.js");
            localeFiles.put("fr_FR", "/assets/jquery/plugins/validate/localization/messages_fr.js");
            localeFiles.put("fr_LU", "/assets/jquery/plugins/validate/localization/messages_fr.js");
            localeFiles.put("fr_CH", "/assets/jquery/plugins/validate/localization/messages_fr.js");
            localeFiles.put("de", "/assets/jquery/plugins/validate/localization/messages_de.js");
            localeFiles.put("de_AT", "/assets/jquery/plugins/validate/localization/messages_de.js");
            localeFiles.put("de_DE", "/assets/jquery/plugins/validate/localization/messages_de.js");
            localeFiles.put("de_LU", "/assets/jquery/plugins/validate/localization/messages_de.js");
            localeFiles.put("de_CH", "/assets/jquery/plugins/validate/localization/messages_de.js");
            localeFiles.put("el", "/assets/jquery/plugins/validate/localization/messages_el.js");
            localeFiles.put("el_CY", "/assets/jquery/plugins/validate/localization/messages_el.js");
            localeFiles.put("el_GR", "/assets/jquery/plugins/validate/localization/messages_el.js");
            localeFiles.put("iw", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("iw_IL", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("hi_IN", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("hu", "/assets/jquery/plugins/validate/localization/messages_hu.js");
            localeFiles.put("hu_HU", "/assets/jquery/plugins/validate/localization/messages_hu.js");
            localeFiles.put("is", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("is_IS", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("in", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("in_ID", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("ga", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("ga_IE", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("it", "/assets/jquery/plugins/validate/localization/messages_it.js");
            localeFiles.put("it_IT", "/assets/jquery/plugins/validate/localization/messages_it.js");
            localeFiles.put("it_CH", "/assets/jquery/plugins/validate/localization/messages_it.js");
            localeFiles.put("ja", "/assets/jquery/plugins/validate/localization/messages_ja.js");
            localeFiles.put("ja_JP", "/assets/jquery/plugins/validate/localization/messages_ja.js");
            localeFiles.put("ja_JP_JP", "/assets/jquery/plugins/validate/localization/messages_ja.js");
            localeFiles.put("ko", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("ko_KR", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("lv", "/assets/jquery/plugins/validate/localization/messages_lv.js");
            localeFiles.put("lv_LV", "/assets/jquery/plugins/validate/localization/messages_lv.js");
            localeFiles.put("lt", "/assets/jquery/plugins/validate/localization/messages_lt.js");
            localeFiles.put("lt_LT", "/assets/jquery/plugins/validate/localization/messages_lt.js");
            localeFiles.put("mk", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("mk_MK", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("ms", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("ms_MY", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("mt", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("mt_MT", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("no", "/assets/jquery/plugins/validate/localization/messages_no.js");
            localeFiles.put("no_NO", "/assets/jquery/plugins/validate/localization/messages_no.js");
            localeFiles.put("no_NO_NY", "/assets/jquery/plugins/validate/localization/messages_no.js");
            localeFiles.put("pl", "/assets/jquery/plugins/validate/localization/messages_pl.js");
            localeFiles.put("pl_PL", "/assets/jquery/plugins/validate/localization/messages_pl.js");
            localeFiles.put("pt", "/assets/jquery/plugins/validate/localization/messages_en.js");
            localeFiles.put("pt_BR", "/assets/jquery/plugins/validate/localization/messages_pt_BR.js");
            localeFiles.put("pt_PT", "/assets/jquery/plugins/validate/localization/messages_pt_PT.js");
            localeFiles.put("ro", "/assets/jquery/plugins/validate/localization/messages_ro.js");
            localeFiles.put("ro_RO", "/assets/jquery/plugins/validate/localization/messages_ro.js");
            localeFiles.put("ru", "/assets/jquery/plugins/validate/localization/messages_ru.js");
            localeFiles.put("ru_RU", "/assets/jquery/plugins/validate/localization/messages_ru.js");
            localeFiles.put("sr", "/assets/jquery/plugins/validate/localization/messages_sr.js");
            localeFiles.put("sr_BA", "/assets/jquery/plugins/validate/localization/messages_sr.js");
            localeFiles.put("sr_ME", "/assets/jquery/plugins/validate/localization/messages_sr.js");
            localeFiles.put("sr_CS", "/assets/jquery/plugins/validate/localization/messages_sr.js");
            localeFiles.put("sr_RS", "/assets/jquery/plugins/validate/localization/messages_sr.js");
            localeFiles.put("sk", "/assets/jquery/plugins/validate/localization/messages_sk.js");
            localeFiles.put("sk_SK", "/assets/jquery/plugins/validate/localization/messages_sk.js");
            localeFiles.put("sl", "/assets/jquery/plugins/validate/localization/messages_sl.js");
            localeFiles.put("sl_SI", "/assets/jquery/plugins/validate/localization/messages_sl.js");
            localeFiles.put("es", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_AR", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_BO", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_CL", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_CO", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_CR", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_DO", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_EC", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_SV", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_GT", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_HN", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_MX", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_NI", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_PA", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_PY", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_PE", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_PR", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_ES", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_US", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_UY", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("es_VE", "/assets/jquery/plugins/validate/localization/messages_es.js");
            localeFiles.put("sv", "/assets/jquery/plugins/validate/localization/messages_sv.js");
            localeFiles.put("sv_SE", "/assets/jquery/plugins/validate/localization/messages_sv.js");
            localeFiles.put("th", "/assets/jquery/plugins/validate/localization/messages_th.js");
            localeFiles.put("th_TH", "/assets/jquery/plugins/validate/localization/messages_th.js");
            localeFiles.put("th_TH_TH", "/assets/jquery/plugins/validate/localization/messages_th.js");
            localeFiles.put("tr", "/assets/jquery/plugins/validate/localization/messages_tr.js");
            localeFiles.put("tr_TR", "/assets/jquery/plugins/validate/localization/messages_tr.js");
            localeFiles.put("uk", "/assets/jquery/plugins/validate/localization/messages_uk.js");
            localeFiles.put("uk_UA", "/assets/jquery/plugins/validate/localization/messages_uk.js");
            localeFiles.put("vi", "/assets/jquery/plugins/validate/localization/messages_vi.js");
            localeFiles.put("vi_VN", "/assets/jquery/plugins/validate/localization/messages_vi.js");
        }

        public static String getFilePath(String locale) {
            if (validation.localeFiles.containsKey(locale)) {
                return validation.localeFiles.get(locale);
            }
            return validation.defaultValidation;
        }
    }

    public static class dateTime {
        private static Map<String, String> localeFiles = new LinkedHashMap<String, String>();
        private static String defaultDateTime = "/assets/webapp/assets/jquery/ui/i18n/jquery.ui.datepicker-en.js";

        static {
            localeFiles.put("sq", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("sq_AL", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_DZ", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_BH", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_EG", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_IQ", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_JO", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_KW", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_LB", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_LY", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_MA", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_OM", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_QA", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_SA", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_SD", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_SY", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_TN", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_AE", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ar_YE", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("be", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("be_BY", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("bg", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-bg.js");
            localeFiles.put("bg_BG", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-bg.js");
            localeFiles.put("ca", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-ca.js");
            localeFiles.put("ca_ES", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-ca.js");
            localeFiles.put("zh", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("zh_CN", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-zh-CN.js");
            localeFiles.put("zh_HK", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-zh-HK.js");
            localeFiles.put("zh_SG", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("zh_TW", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-zh-TW.js");
            localeFiles.put("hr", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-hr.js");
            localeFiles.put("hr_HR", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-hr.js");
            localeFiles.put("cs", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-cs.js");
            localeFiles.put("cs_CZ", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-cs.js");
            localeFiles.put("da", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-da.js");
            localeFiles.put("da_DK", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-da.js");
            localeFiles.put("nl", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-nl.js");
            localeFiles.put("nl_BE", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-nl.js");
            localeFiles.put("nl_NL", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-nl.js");
            localeFiles.put("en", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("en_AU", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("en_CA", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("en_IN", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("en_IE", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("en_MT", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("en_NZ", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("en_PH", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("en_SG", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("en_ZA", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("en_GB", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("en_US", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("et", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-et.js");
            localeFiles.put("et_EE", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-et.js");
            localeFiles.put("fi", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-fi.js");
            localeFiles.put("fi_FI", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-fi.js");
            localeFiles.put("fr", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-fr.js");
            localeFiles.put("fr_BE", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-fr.js");
            localeFiles.put("fr_CA", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-fr.js");
            localeFiles.put("fr_FR", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-fr.js");
            localeFiles.put("fr_LU", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-fr.js");
            localeFiles.put("fr_CH", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-fr.js");
            localeFiles.put("de", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-de.js");
            localeFiles.put("de_AT", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-de.js");
            localeFiles.put("de_DE", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-de.js");
            localeFiles.put("de_LU", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-de.js");
            localeFiles.put("de_CH", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-de.js");
            localeFiles.put("el", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-el.js");
            localeFiles.put("el_CY", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-el.js");
            localeFiles.put("el_GR", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-el.js");
            localeFiles.put("iw", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("iw_IL", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("hi_IN", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("hu", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-hu.js");
            localeFiles.put("hu_HU", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-hu.js");
            localeFiles.put("is", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("is_IS", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("in", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("in_ID", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ga", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ga_IE", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("it", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-it.js");
            localeFiles.put("it_IT", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-it.js");
            localeFiles.put("it_CH", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-it.js");
            localeFiles.put("ja", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-ja.js");
            localeFiles.put("ja_JP", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-ja.js");
            localeFiles.put("ja_JP_JP", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-ja.js");
            localeFiles.put("ko", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-ko.js");
            localeFiles.put("ko_KR", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-ko.js");
            localeFiles.put("lv", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("lv_LV", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("lt", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-lt.js");
            localeFiles.put("lt_LT", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-lt.js");
            localeFiles.put("mk", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("mk_MK", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ms", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("ms_MY", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("mt", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("mt_MT", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("no", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-no.js");
            localeFiles.put("no_NO", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-no.js");
            localeFiles.put("no_NO_NY", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-no.js");
            localeFiles.put("pl", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-pl.js");
            localeFiles.put("pl_PL", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-pl.js");
            localeFiles.put("pt", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-pt.js");
            localeFiles.put("pt_BR", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-pt.js");
            localeFiles.put("pt_PT", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-pt.js");
            localeFiles.put("ro", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-ro.js");
            localeFiles.put("ro_RO", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-ro.js");
            localeFiles.put("ru", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-ru.js");
            localeFiles.put("ru_RU", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-ru.js");
            localeFiles.put("sr", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("sr_BA", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("sr_ME", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("sr_CS", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("sr_RS", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-sr-RS.js");
            localeFiles.put("sk", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-sk.js");
            localeFiles.put("sk_SK", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-sk.js");
            localeFiles.put("sl", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("sl_SI", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-en.js");
            localeFiles.put("es", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_AR", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_BO", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_CL", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_CO", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_CR", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_DO", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_EC", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_SV", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_GT", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_HN", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_MX", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_NI", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_PA", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_PY", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_PE", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_PR", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_ES", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_US", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_UY", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("es_VE", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-es.js");
            localeFiles.put("sv", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-sv.js");
            localeFiles.put("sv_SE", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-sv.js");
            localeFiles.put("th", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-th.js");
            localeFiles.put("th_TH", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-th.js");
            localeFiles.put("th_TH_TH", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-th.js");
            localeFiles.put("tr", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-tr.js");
            localeFiles.put("tr_TR", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-tr.js");
            localeFiles.put("uk", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-uk.js");
            localeFiles.put("uk_UA", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-uk.js");
            localeFiles.put("vi", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-vi.js");
            localeFiles.put("vi_VN", "/assets/jquery/plugins/datetimepicker/localization/jquery-ui-timepicker-vi.js");
        }

        public static String getFilePath(String locale) {
            if (dateTime.localeFiles.containsKey(locale)) {
                return dateTime.localeFiles.get(locale);
            }
            return dateTime.defaultDateTime;
        }
    }
}
